# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import unitedShieldSpace_pb2 as unitedShieldSpace__pb2


class UnitedShieldSpaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterNewUser = channel.unary_unary(
        '/unitedshieldspace.UnitedShieldSpace/RegisterNewUser',
        request_serializer=unitedShieldSpace__pb2.NewUserDetails.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.UserCreationStatus.FromString,
        )
    self.LoginUser = channel.unary_unary(
        '/unitedshieldspace.UnitedShieldSpace/LoginUser',
        request_serializer=unitedShieldSpace__pb2.UserCredentials.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.LoginResponse.FromString,
        )


class UnitedShieldSpaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterNewUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoginUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UnitedShieldSpaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterNewUser': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterNewUser,
          request_deserializer=unitedShieldSpace__pb2.NewUserDetails.FromString,
          response_serializer=unitedShieldSpace__pb2.UserCreationStatus.SerializeToString,
      ),
      'LoginUser': grpc.unary_unary_rpc_method_handler(
          servicer.LoginUser,
          request_deserializer=unitedShieldSpace__pb2.UserCredentials.FromString,
          response_serializer=unitedShieldSpace__pb2.LoginResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'unitedshieldspace.UnitedShieldSpace', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
