# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unitedShieldSpace.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unitedShieldSpace.proto',
  package='unitedshieldspace',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17unitedShieldSpace.proto\x12\x11unitedshieldspace\"?\n\x0eNewUserDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\")\n\x12UserCreationStatus\x12\x13\n\x0buserCreated\x18\x01 \x01(\x08\x32p\n\x11UnitedShieldSpace\x12[\n\x0fRegisterNewUser\x12!.unitedshieldspace.NewUserDetails\x1a%.unitedshieldspace.UserCreationStatusb\x06proto3'
)




_NEWUSERDETAILS = _descriptor.Descriptor(
  name='NewUserDetails',
  full_name='unitedshieldspace.NewUserDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='unitedshieldspace.NewUserDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='unitedshieldspace.NewUserDetails.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='unitedshieldspace.NewUserDetails.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=109,
)


_USERCREATIONSTATUS = _descriptor.Descriptor(
  name='UserCreationStatus',
  full_name='unitedshieldspace.UserCreationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userCreated', full_name='unitedshieldspace.UserCreationStatus.userCreated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['NewUserDetails'] = _NEWUSERDETAILS
DESCRIPTOR.message_types_by_name['UserCreationStatus'] = _USERCREATIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewUserDetails = _reflection.GeneratedProtocolMessageType('NewUserDetails', (_message.Message,), {
  'DESCRIPTOR' : _NEWUSERDETAILS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.NewUserDetails)
  })
_sym_db.RegisterMessage(NewUserDetails)

UserCreationStatus = _reflection.GeneratedProtocolMessageType('UserCreationStatus', (_message.Message,), {
  'DESCRIPTOR' : _USERCREATIONSTATUS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.UserCreationStatus)
  })
_sym_db.RegisterMessage(UserCreationStatus)



_UNITEDSHIELDSPACE = _descriptor.ServiceDescriptor(
  name='UnitedShieldSpace',
  full_name='unitedshieldspace.UnitedShieldSpace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=154,
  serialized_end=266,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNewUser',
    full_name='unitedshieldspace.UnitedShieldSpace.RegisterNewUser',
    index=0,
    containing_service=None,
    input_type=_NEWUSERDETAILS,
    output_type=_USERCREATIONSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNITEDSHIELDSPACE)

DESCRIPTOR.services_by_name['UnitedShieldSpace'] = _UNITEDSHIELDSPACE

# @@protoc_insertion_point(module_scope)
