# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import unitedShieldSpace_pb2 as unitedShieldSpace__pb2


class UnitedShieldSpaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterNewUser = channel.unary_unary(
        '/unitedshieldspace.UnitedShieldSpace/RegisterNewUser',
        request_serializer=unitedShieldSpace__pb2.NewUserDetails.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.UserCreationStatus.FromString,
        )
    self.LoginUser = channel.unary_unary(
        '/unitedshieldspace.UnitedShieldSpace/LoginUser',
        request_serializer=unitedShieldSpace__pb2.UserCredentials.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.LoginResponse.FromString,
        )
    self.GetNewTokens = channel.unary_unary(
        '/unitedshieldspace.UnitedShieldSpace/GetNewTokens',
        request_serializer=unitedShieldSpace__pb2.RefreshTokenDetails.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.NewTokens.FromString,
        )
    self.UploadFile = channel.stream_unary(
        '/unitedshieldspace.UnitedShieldSpace/UploadFile',
        request_serializer=unitedShieldSpace__pb2.FileSegment.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.UploadStatus.FromString,
        )
    self.ListUserFiles = channel.unary_stream(
        '/unitedshieldspace.UnitedShieldSpace/ListUserFiles',
        request_serializer=unitedShieldSpace__pb2.UserDetails.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.FileDetails.FromString,
        )
    self.ListSharedWithMeFiles = channel.unary_stream(
        '/unitedshieldspace.UnitedShieldSpace/ListSharedWithMeFiles',
        request_serializer=unitedShieldSpace__pb2.UserDetails.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.ExtFileDetails.FromString,
        )
    self.UpdateACL = channel.unary_unary(
        '/unitedshieldspace.UnitedShieldSpace/UpdateACL',
        request_serializer=unitedShieldSpace__pb2.ACLDetails.SerializeToString,
        response_deserializer=unitedShieldSpace__pb2.ACLUpdateResponse.FromString,
        )


class UnitedShieldSpaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterNewUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoginUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNewTokens(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListUserFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSharedWithMeFiles(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateACL(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UnitedShieldSpaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterNewUser': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterNewUser,
          request_deserializer=unitedShieldSpace__pb2.NewUserDetails.FromString,
          response_serializer=unitedShieldSpace__pb2.UserCreationStatus.SerializeToString,
      ),
      'LoginUser': grpc.unary_unary_rpc_method_handler(
          servicer.LoginUser,
          request_deserializer=unitedShieldSpace__pb2.UserCredentials.FromString,
          response_serializer=unitedShieldSpace__pb2.LoginResponse.SerializeToString,
      ),
      'GetNewTokens': grpc.unary_unary_rpc_method_handler(
          servicer.GetNewTokens,
          request_deserializer=unitedShieldSpace__pb2.RefreshTokenDetails.FromString,
          response_serializer=unitedShieldSpace__pb2.NewTokens.SerializeToString,
      ),
      'UploadFile': grpc.stream_unary_rpc_method_handler(
          servicer.UploadFile,
          request_deserializer=unitedShieldSpace__pb2.FileSegment.FromString,
          response_serializer=unitedShieldSpace__pb2.UploadStatus.SerializeToString,
      ),
      'ListUserFiles': grpc.unary_stream_rpc_method_handler(
          servicer.ListUserFiles,
          request_deserializer=unitedShieldSpace__pb2.UserDetails.FromString,
          response_serializer=unitedShieldSpace__pb2.FileDetails.SerializeToString,
      ),
      'ListSharedWithMeFiles': grpc.unary_stream_rpc_method_handler(
          servicer.ListSharedWithMeFiles,
          request_deserializer=unitedShieldSpace__pb2.UserDetails.FromString,
          response_serializer=unitedShieldSpace__pb2.ExtFileDetails.SerializeToString,
      ),
      'UpdateACL': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateACL,
          request_deserializer=unitedShieldSpace__pb2.ACLDetails.FromString,
          response_serializer=unitedShieldSpace__pb2.ACLUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'unitedshieldspace.UnitedShieldSpace', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
