# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unitedShieldSpace.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unitedShieldSpace.proto',
  package='unitedshieldspace',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17unitedShieldSpace.proto\x12\x11unitedshieldspace\"?\n\x0eNewUserDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\")\n\x12UserCreationStatus\x12\x13\n\x0buserCreated\x18\x01 \x01(\x08\"2\n\x0fUserCredentials\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"j\n\rLoginResponse\x12\x13\n\x0bloginStatus\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x04 \x01(\t\x12\x14\n\x0crefreshToken\x18\x05 \x01(\t\"8\n\x13RefreshTokenDetails\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t\"6\n\tNewTokens\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t\"Z\n\x0b\x46ileSegment\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x03 \x01(\t\x12\x17\n\x0f\x66ileSegmentData\x18\x04 \x01(\x0c\"$\n\x0cUploadStatus\x12\x14\n\x0cuploadStatus\x18\x01 \x01(\x08\x32\xea\x02\n\x11UnitedShieldSpace\x12[\n\x0fRegisterNewUser\x12!.unitedshieldspace.NewUserDetails\x1a%.unitedshieldspace.UserCreationStatus\x12Q\n\tLoginUser\x12\".unitedshieldspace.UserCredentials\x1a .unitedshieldspace.LoginResponse\x12T\n\x0cGetNewTokens\x12&.unitedshieldspace.RefreshTokenDetails\x1a\x1c.unitedshieldspace.NewTokens\x12O\n\nUploadFile\x12\x1e.unitedshieldspace.FileSegment\x1a\x1f.unitedshieldspace.UploadStatus(\x01\x62\x06proto3'
)




_NEWUSERDETAILS = _descriptor.Descriptor(
  name='NewUserDetails',
  full_name='unitedshieldspace.NewUserDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='unitedshieldspace.NewUserDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='unitedshieldspace.NewUserDetails.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='unitedshieldspace.NewUserDetails.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=109,
)


_USERCREATIONSTATUS = _descriptor.Descriptor(
  name='UserCreationStatus',
  full_name='unitedshieldspace.UserCreationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userCreated', full_name='unitedshieldspace.UserCreationStatus.userCreated', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=152,
)


_USERCREDENTIALS = _descriptor.Descriptor(
  name='UserCredentials',
  full_name='unitedshieldspace.UserCredentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='unitedshieldspace.UserCredentials.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='unitedshieldspace.UserCredentials.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=204,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='unitedshieldspace.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginStatus', full_name='unitedshieldspace.LoginResponse.loginStatus', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='unitedshieldspace.LoginResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='unitedshieldspace.LoginResponse.uid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='unitedshieldspace.LoginResponse.accessToken', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refreshToken', full_name='unitedshieldspace.LoginResponse.refreshToken', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=312,
)


_REFRESHTOKENDETAILS = _descriptor.Descriptor(
  name='RefreshTokenDetails',
  full_name='unitedshieldspace.RefreshTokenDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='unitedshieldspace.RefreshTokenDetails.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refreshToken', full_name='unitedshieldspace.RefreshTokenDetails.refreshToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=370,
)


_NEWTOKENS = _descriptor.Descriptor(
  name='NewTokens',
  full_name='unitedshieldspace.NewTokens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='unitedshieldspace.NewTokens.accessToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refreshToken', full_name='unitedshieldspace.NewTokens.refreshToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=426,
)


_FILESEGMENT = _descriptor.Descriptor(
  name='FileSegment',
  full_name='unitedshieldspace.FileSegment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='unitedshieldspace.FileSegment.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileName', full_name='unitedshieldspace.FileSegment.fileName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='unitedshieldspace.FileSegment.accessToken', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileSegmentData', full_name='unitedshieldspace.FileSegment.fileSegmentData', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=518,
)


_UPLOADSTATUS = _descriptor.Descriptor(
  name='UploadStatus',
  full_name='unitedshieldspace.UploadStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uploadStatus', full_name='unitedshieldspace.UploadStatus.uploadStatus', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=556,
)

DESCRIPTOR.message_types_by_name['NewUserDetails'] = _NEWUSERDETAILS
DESCRIPTOR.message_types_by_name['UserCreationStatus'] = _USERCREATIONSTATUS
DESCRIPTOR.message_types_by_name['UserCredentials'] = _USERCREDENTIALS
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['RefreshTokenDetails'] = _REFRESHTOKENDETAILS
DESCRIPTOR.message_types_by_name['NewTokens'] = _NEWTOKENS
DESCRIPTOR.message_types_by_name['FileSegment'] = _FILESEGMENT
DESCRIPTOR.message_types_by_name['UploadStatus'] = _UPLOADSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewUserDetails = _reflection.GeneratedProtocolMessageType('NewUserDetails', (_message.Message,), {
  'DESCRIPTOR' : _NEWUSERDETAILS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.NewUserDetails)
  })
_sym_db.RegisterMessage(NewUserDetails)

UserCreationStatus = _reflection.GeneratedProtocolMessageType('UserCreationStatus', (_message.Message,), {
  'DESCRIPTOR' : _USERCREATIONSTATUS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.UserCreationStatus)
  })
_sym_db.RegisterMessage(UserCreationStatus)

UserCredentials = _reflection.GeneratedProtocolMessageType('UserCredentials', (_message.Message,), {
  'DESCRIPTOR' : _USERCREDENTIALS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.UserCredentials)
  })
_sym_db.RegisterMessage(UserCredentials)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

RefreshTokenDetails = _reflection.GeneratedProtocolMessageType('RefreshTokenDetails', (_message.Message,), {
  'DESCRIPTOR' : _REFRESHTOKENDETAILS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.RefreshTokenDetails)
  })
_sym_db.RegisterMessage(RefreshTokenDetails)

NewTokens = _reflection.GeneratedProtocolMessageType('NewTokens', (_message.Message,), {
  'DESCRIPTOR' : _NEWTOKENS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.NewTokens)
  })
_sym_db.RegisterMessage(NewTokens)

FileSegment = _reflection.GeneratedProtocolMessageType('FileSegment', (_message.Message,), {
  'DESCRIPTOR' : _FILESEGMENT,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.FileSegment)
  })
_sym_db.RegisterMessage(FileSegment)

UploadStatus = _reflection.GeneratedProtocolMessageType('UploadStatus', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADSTATUS,
  '__module__' : 'unitedShieldSpace_pb2'
  # @@protoc_insertion_point(class_scope:unitedshieldspace.UploadStatus)
  })
_sym_db.RegisterMessage(UploadStatus)



_UNITEDSHIELDSPACE = _descriptor.ServiceDescriptor(
  name='UnitedShieldSpace',
  full_name='unitedshieldspace.UnitedShieldSpace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=559,
  serialized_end=921,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNewUser',
    full_name='unitedshieldspace.UnitedShieldSpace.RegisterNewUser',
    index=0,
    containing_service=None,
    input_type=_NEWUSERDETAILS,
    output_type=_USERCREATIONSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LoginUser',
    full_name='unitedshieldspace.UnitedShieldSpace.LoginUser',
    index=1,
    containing_service=None,
    input_type=_USERCREDENTIALS,
    output_type=_LOGINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNewTokens',
    full_name='unitedshieldspace.UnitedShieldSpace.GetNewTokens',
    index=2,
    containing_service=None,
    input_type=_REFRESHTOKENDETAILS,
    output_type=_NEWTOKENS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UploadFile',
    full_name='unitedshieldspace.UnitedShieldSpace.UploadFile',
    index=3,
    containing_service=None,
    input_type=_FILESEGMENT,
    output_type=_UPLOADSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UNITEDSHIELDSPACE)

DESCRIPTOR.services_by_name['UnitedShieldSpace'] = _UNITEDSHIELDSPACE

# @@protoc_insertion_point(module_scope)
