// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unitedShieldSpace.proto

package unitedshieldspace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUserDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserDetails) Reset()         { *m = NewUserDetails{} }
func (m *NewUserDetails) String() string { return proto.CompactTextString(m) }
func (*NewUserDetails) ProtoMessage()    {}
func (*NewUserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{0}
}

func (m *NewUserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserDetails.Unmarshal(m, b)
}
func (m *NewUserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserDetails.Marshal(b, m, deterministic)
}
func (m *NewUserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserDetails.Merge(m, src)
}
func (m *NewUserDetails) XXX_Size() int {
	return xxx_messageInfo_NewUserDetails.Size(m)
}
func (m *NewUserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserDetails proto.InternalMessageInfo

func (m *NewUserDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserDetails) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserCreationStatus struct {
	UserCreated          bool     `protobuf:"varint,1,opt,name=userCreated,proto3" json:"userCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreationStatus) Reset()         { *m = UserCreationStatus{} }
func (m *UserCreationStatus) String() string { return proto.CompactTextString(m) }
func (*UserCreationStatus) ProtoMessage()    {}
func (*UserCreationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{1}
}

func (m *UserCreationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreationStatus.Unmarshal(m, b)
}
func (m *UserCreationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreationStatus.Marshal(b, m, deterministic)
}
func (m *UserCreationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreationStatus.Merge(m, src)
}
func (m *UserCreationStatus) XXX_Size() int {
	return xxx_messageInfo_UserCreationStatus.Size(m)
}
func (m *UserCreationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreationStatus proto.InternalMessageInfo

func (m *UserCreationStatus) GetUserCreated() bool {
	if m != nil {
		return m.UserCreated
	}
	return false
}

type UserCredentials struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredentials) Reset()         { *m = UserCredentials{} }
func (m *UserCredentials) String() string { return proto.CompactTextString(m) }
func (*UserCredentials) ProtoMessage()    {}
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{2}
}

func (m *UserCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredentials.Unmarshal(m, b)
}
func (m *UserCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredentials.Marshal(b, m, deterministic)
}
func (m *UserCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredentials.Merge(m, src)
}
func (m *UserCredentials) XXX_Size() int {
	return xxx_messageInfo_UserCredentials.Size(m)
}
func (m *UserCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredentials proto.InternalMessageInfo

func (m *UserCredentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	LoginStatus          bool     `protobuf:"varint,1,opt,name=loginStatus,proto3" json:"loginStatus,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	AccessToken          string   `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,5,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetLoginStatus() bool {
	if m != nil {
		return m.LoginStatus
	}
	return false
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserDetails)(nil), "unitedshieldspace.NewUserDetails")
	proto.RegisterType((*UserCreationStatus)(nil), "unitedshieldspace.UserCreationStatus")
	proto.RegisterType((*UserCredentials)(nil), "unitedshieldspace.UserCredentials")
	proto.RegisterType((*LoginResponse)(nil), "unitedshieldspace.LoginResponse")
}

func init() {
	proto.RegisterFile("unitedShieldSpace.proto", fileDescriptor_e766365d0c253d38)
}

var fileDescriptor_e766365d0c253d38 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xfa, 0xf3, 0xa9, 0xdd, 0x0f, 0x28, 0xb5, 0x90, 0x88, 0x72, 0x0a, 0x91, 0x90, 0x38,
	0xe5, 0x00, 0x12, 0x2f, 0x50, 0x8e, 0x08, 0x89, 0x84, 0x72, 0xe1, 0x64, 0x92, 0xa5, 0xb5, 0x48,
	0xed, 0xc8, 0xeb, 0xa8, 0x4f, 0xc3, 0xd3, 0xf0, 0x62, 0xc8, 0x4e, 0x53, 0x92, 0x92, 0xde, 0xec,
	0x99, 0xf1, 0x4e, 0x76, 0x26, 0x70, 0x59, 0x49, 0x61, 0x30, 0x4f, 0xd7, 0x02, 0x8b, 0x3c, 0x2d,
	0x79, 0x86, 0x71, 0xa9, 0x95, 0x51, 0x6c, 0x5e, 0x13, 0xe4, 0x08, 0xb2, 0x44, 0xf4, 0x0a, 0x67,
	0x4f, 0xb8, 0x5d, 0x12, 0xea, 0x07, 0x34, 0x5c, 0x14, 0xc4, 0x18, 0x8c, 0x24, 0xdf, 0xa0, 0xef,
	0x85, 0xde, 0xcd, 0x34, 0x71, 0x67, 0x76, 0x01, 0x63, 0xdc, 0x70, 0x51, 0xf8, 0x03, 0x07, 0xd6,
	0x17, 0x16, 0xc0, 0xa4, 0xe4, 0x44, 0x5b, 0xa5, 0x73, 0x7f, 0xe8, 0x88, 0xfd, 0x3d, 0xba, 0x07,
	0x66, 0x87, 0x2e, 0x34, 0x72, 0x23, 0x94, 0x4c, 0x0d, 0x37, 0x15, 0xb1, 0x10, 0xfe, 0x57, 0x0d,
	0x8a, 0xb9, 0xb3, 0x98, 0x24, 0x6d, 0x28, 0x5a, 0xc0, 0x6c, 0xf7, 0x2e, 0x47, 0x69, 0x04, 0x2f,
	0xe8, 0xd7, 0xdc, 0x3b, 0x66, 0x3e, 0x38, 0x30, 0xff, 0xf2, 0xe0, 0xf4, 0x51, 0xad, 0x84, 0x4c,
	0x90, 0x4a, 0x25, 0x09, 0xad, 0x71, 0x61, 0x81, 0xfa, 0x3b, 0x1a, 0xe3, 0x16, 0xb4, 0x5f, 0x7b,
	0xd0, 0x5a, 0xfb, 0x1c, 0x86, 0x95, 0x68, 0x76, 0xb3, 0x47, 0x3b, 0x87, 0x67, 0x19, 0x12, 0xbd,
	0xa8, 0x4f, 0x94, 0xfe, 0xc8, 0x31, 0x6d, 0x88, 0x45, 0x70, 0xa2, 0xf1, 0x43, 0x23, 0xad, 0x6b,
	0xc9, 0xd8, 0x49, 0x3a, 0xd8, 0xed, 0xb7, 0x07, 0xf3, 0xe5, 0x61, 0x47, 0xec, 0x0d, 0x66, 0x09,
	0xae, 0x04, 0x19, 0xd4, 0xbb, 0x4a, 0xd8, 0x55, 0xfc, 0xa7, 0xb1, 0xb8, 0x5b, 0x57, 0x70, 0xdd,
	0x23, 0xe9, 0x49, 0xfe, 0x19, 0xa6, 0x2e, 0x11, 0x37, 0x36, 0x3a, 0xfe, 0xa6, 0x49, 0x3d, 0x08,
	0x7b, 0x34, 0x9d, 0x4c, 0xdf, 0xff, 0xb9, 0x9f, 0xea, 0xee, 0x27, 0x00, 0x00, 0xff, 0xff, 0x45,
	0xba, 0x7e, 0x84, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UnitedShieldSpaceClient is the client API for UnitedShieldSpace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnitedShieldSpaceClient interface {
	RegisterNewUser(ctx context.Context, in *NewUserDetails, opts ...grpc.CallOption) (*UserCreationStatus, error)
	LoginUser(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*LoginResponse, error)
}

type unitedShieldSpaceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnitedShieldSpaceClient(cc grpc.ClientConnInterface) UnitedShieldSpaceClient {
	return &unitedShieldSpaceClient{cc}
}

func (c *unitedShieldSpaceClient) RegisterNewUser(ctx context.Context, in *NewUserDetails, opts ...grpc.CallOption) (*UserCreationStatus, error) {
	out := new(UserCreationStatus)
	err := c.cc.Invoke(ctx, "/unitedshieldspace.UnitedShieldSpace/RegisterNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitedShieldSpaceClient) LoginUser(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/unitedshieldspace.UnitedShieldSpace/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnitedShieldSpaceServer is the server API for UnitedShieldSpace service.
type UnitedShieldSpaceServer interface {
	RegisterNewUser(context.Context, *NewUserDetails) (*UserCreationStatus, error)
	LoginUser(context.Context, *UserCredentials) (*LoginResponse, error)
}

// UnimplementedUnitedShieldSpaceServer can be embedded to have forward compatible implementations.
type UnimplementedUnitedShieldSpaceServer struct {
}

func (*UnimplementedUnitedShieldSpaceServer) RegisterNewUser(ctx context.Context, req *NewUserDetails) (*UserCreationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewUser not implemented")
}
func (*UnimplementedUnitedShieldSpaceServer) LoginUser(ctx context.Context, req *UserCredentials) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}

func RegisterUnitedShieldSpaceServer(s *grpc.Server, srv UnitedShieldSpaceServer) {
	s.RegisterService(&_UnitedShieldSpace_serviceDesc, srv)
}

func _UnitedShieldSpace_RegisterNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitedShieldSpaceServer).RegisterNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitedshieldspace.UnitedShieldSpace/RegisterNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitedShieldSpaceServer).RegisterNewUser(ctx, req.(*NewUserDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitedShieldSpace_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitedShieldSpaceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitedshieldspace.UnitedShieldSpace/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitedShieldSpaceServer).LoginUser(ctx, req.(*UserCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnitedShieldSpace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unitedshieldspace.UnitedShieldSpace",
	HandlerType: (*UnitedShieldSpaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewUser",
			Handler:    _UnitedShieldSpace_RegisterNewUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UnitedShieldSpace_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unitedShieldSpace.proto",
}
