// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unitedShieldSpace.proto

package unitedshieldspace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUserDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserDetails) Reset()         { *m = NewUserDetails{} }
func (m *NewUserDetails) String() string { return proto.CompactTextString(m) }
func (*NewUserDetails) ProtoMessage()    {}
func (*NewUserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{0}
}

func (m *NewUserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserDetails.Unmarshal(m, b)
}
func (m *NewUserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserDetails.Marshal(b, m, deterministic)
}
func (m *NewUserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserDetails.Merge(m, src)
}
func (m *NewUserDetails) XXX_Size() int {
	return xxx_messageInfo_NewUserDetails.Size(m)
}
func (m *NewUserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserDetails proto.InternalMessageInfo

func (m *NewUserDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUserDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUserDetails) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserCreationStatus struct {
	UserCreated          bool     `protobuf:"varint,1,opt,name=userCreated,proto3" json:"userCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreationStatus) Reset()         { *m = UserCreationStatus{} }
func (m *UserCreationStatus) String() string { return proto.CompactTextString(m) }
func (*UserCreationStatus) ProtoMessage()    {}
func (*UserCreationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{1}
}

func (m *UserCreationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreationStatus.Unmarshal(m, b)
}
func (m *UserCreationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreationStatus.Marshal(b, m, deterministic)
}
func (m *UserCreationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreationStatus.Merge(m, src)
}
func (m *UserCreationStatus) XXX_Size() int {
	return xxx_messageInfo_UserCreationStatus.Size(m)
}
func (m *UserCreationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreationStatus proto.InternalMessageInfo

func (m *UserCreationStatus) GetUserCreated() bool {
	if m != nil {
		return m.UserCreated
	}
	return false
}

type UserCredentials struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredentials) Reset()         { *m = UserCredentials{} }
func (m *UserCredentials) String() string { return proto.CompactTextString(m) }
func (*UserCredentials) ProtoMessage()    {}
func (*UserCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{2}
}

func (m *UserCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredentials.Unmarshal(m, b)
}
func (m *UserCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredentials.Marshal(b, m, deterministic)
}
func (m *UserCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredentials.Merge(m, src)
}
func (m *UserCredentials) XXX_Size() int {
	return xxx_messageInfo_UserCredentials.Size(m)
}
func (m *UserCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredentials proto.InternalMessageInfo

func (m *UserCredentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCredentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	LoginStatus          bool     `protobuf:"varint,1,opt,name=loginStatus,proto3" json:"loginStatus,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	AccessToken          string   `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,5,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetLoginStatus() bool {
	if m != nil {
		return m.LoginStatus
	}
	return false
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenDetails struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenDetails) Reset()         { *m = RefreshTokenDetails{} }
func (m *RefreshTokenDetails) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenDetails) ProtoMessage()    {}
func (*RefreshTokenDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{4}
}

func (m *RefreshTokenDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenDetails.Unmarshal(m, b)
}
func (m *RefreshTokenDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenDetails.Marshal(b, m, deterministic)
}
func (m *RefreshTokenDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenDetails.Merge(m, src)
}
func (m *RefreshTokenDetails) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenDetails.Size(m)
}
func (m *RefreshTokenDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenDetails proto.InternalMessageInfo

func (m *RefreshTokenDetails) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RefreshTokenDetails) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type NewTokens struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTokens) Reset()         { *m = NewTokens{} }
func (m *NewTokens) String() string { return proto.CompactTextString(m) }
func (*NewTokens) ProtoMessage()    {}
func (*NewTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{5}
}

func (m *NewTokens) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTokens.Unmarshal(m, b)
}
func (m *NewTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTokens.Marshal(b, m, deterministic)
}
func (m *NewTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTokens.Merge(m, src)
}
func (m *NewTokens) XXX_Size() int {
	return xxx_messageInfo_NewTokens.Size(m)
}
func (m *NewTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTokens.DiscardUnknown(m)
}

var xxx_messageInfo_NewTokens proto.InternalMessageInfo

func (m *NewTokens) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *NewTokens) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type FileSegment struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	AccessToken          string   `protobuf:"bytes,4,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	FileSegmentData      []byte   `protobuf:"bytes,5,opt,name=fileSegmentData,proto3" json:"fileSegmentData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileSegment) Reset()         { *m = FileSegment{} }
func (m *FileSegment) String() string { return proto.CompactTextString(m) }
func (*FileSegment) ProtoMessage()    {}
func (*FileSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{6}
}

func (m *FileSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSegment.Unmarshal(m, b)
}
func (m *FileSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSegment.Marshal(b, m, deterministic)
}
func (m *FileSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSegment.Merge(m, src)
}
func (m *FileSegment) XXX_Size() int {
	return xxx_messageInfo_FileSegment.Size(m)
}
func (m *FileSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FileSegment proto.InternalMessageInfo

func (m *FileSegment) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FileSegment) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *FileSegment) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileSegment) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *FileSegment) GetFileSegmentData() []byte {
	if m != nil {
		return m.FileSegmentData
	}
	return nil
}

type UploadStatus struct {
	UploadStatus         bool     `protobuf:"varint,1,opt,name=uploadStatus,proto3" json:"uploadStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadStatus) Reset()         { *m = UploadStatus{} }
func (m *UploadStatus) String() string { return proto.CompactTextString(m) }
func (*UploadStatus) ProtoMessage()    {}
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{7}
}

func (m *UploadStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadStatus.Unmarshal(m, b)
}
func (m *UploadStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadStatus.Marshal(b, m, deterministic)
}
func (m *UploadStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadStatus.Merge(m, src)
}
func (m *UploadStatus) XXX_Size() int {
	return xxx_messageInfo_UploadStatus.Size(m)
}
func (m *UploadStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UploadStatus proto.InternalMessageInfo

func (m *UploadStatus) GetUploadStatus() bool {
	if m != nil {
		return m.UploadStatus
	}
	return false
}

type UserDetails struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{8}
}

func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserDetails) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type FileDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedOn            int64    `protobuf:"varint,2,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDetails) Reset()         { *m = FileDetails{} }
func (m *FileDetails) String() string { return proto.CompactTextString(m) }
func (*FileDetails) ProtoMessage()    {}
func (*FileDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{9}
}

func (m *FileDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDetails.Unmarshal(m, b)
}
func (m *FileDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDetails.Marshal(b, m, deterministic)
}
func (m *FileDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDetails.Merge(m, src)
}
func (m *FileDetails) XXX_Size() int {
	return xxx_messageInfo_FileDetails.Size(m)
}
func (m *FileDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDetails.DiscardUnknown(m)
}

var xxx_messageInfo_FileDetails proto.InternalMessageInfo

func (m *FileDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileDetails) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

type ExtFileDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtFileDetails) Reset()         { *m = ExtFileDetails{} }
func (m *ExtFileDetails) String() string { return proto.CompactTextString(m) }
func (*ExtFileDetails) ProtoMessage()    {}
func (*ExtFileDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e766365d0c253d38, []int{10}
}

func (m *ExtFileDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtFileDetails.Unmarshal(m, b)
}
func (m *ExtFileDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtFileDetails.Marshal(b, m, deterministic)
}
func (m *ExtFileDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtFileDetails.Merge(m, src)
}
func (m *ExtFileDetails) XXX_Size() int {
	return xxx_messageInfo_ExtFileDetails.Size(m)
}
func (m *ExtFileDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtFileDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ExtFileDetails proto.InternalMessageInfo

func (m *ExtFileDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExtFileDetails) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ExtFileDetails) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func init() {
	proto.RegisterType((*NewUserDetails)(nil), "unitedshieldspace.NewUserDetails")
	proto.RegisterType((*UserCreationStatus)(nil), "unitedshieldspace.UserCreationStatus")
	proto.RegisterType((*UserCredentials)(nil), "unitedshieldspace.UserCredentials")
	proto.RegisterType((*LoginResponse)(nil), "unitedshieldspace.LoginResponse")
	proto.RegisterType((*RefreshTokenDetails)(nil), "unitedshieldspace.RefreshTokenDetails")
	proto.RegisterType((*NewTokens)(nil), "unitedshieldspace.NewTokens")
	proto.RegisterType((*FileSegment)(nil), "unitedshieldspace.FileSegment")
	proto.RegisterType((*UploadStatus)(nil), "unitedshieldspace.UploadStatus")
	proto.RegisterType((*UserDetails)(nil), "unitedshieldspace.UserDetails")
	proto.RegisterType((*FileDetails)(nil), "unitedshieldspace.FileDetails")
	proto.RegisterType((*ExtFileDetails)(nil), "unitedshieldspace.ExtFileDetails")
}

func init() {
	proto.RegisterFile("unitedShieldSpace.proto", fileDescriptor_e766365d0c253d38)
}

var fileDescriptor_e766365d0c253d38 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0xd2, 0x16, 0xb5, 0xd7, 0x6e, 0x65, 0x66, 0x88, 0x2a, 0x9a, 0xa0, 0x58, 0x02, 0xf5,
	0xa9, 0x9a, 0x86, 0xc4, 0x2b, 0x0f, 0xdb, 0xe0, 0x81, 0xd1, 0xa9, 0xe9, 0x0a, 0x48, 0xf0, 0x62,
	0x9a, 0x6b, 0x6b, 0x91, 0x26, 0x55, 0xec, 0xa8, 0xfc, 0x17, 0xb4, 0xff, 0x8a, 0xec, 0x24, 0x8b,
	0x93, 0xb9, 0x6c, 0x6f, 0xbe, 0xef, 0xce, 0xdf, 0x77, 0x77, 0xbe, 0x4b, 0xe0, 0x45, 0x1a, 0x71,
	0x89, 0xc1, 0x6c, 0xcd, 0x31, 0x0c, 0x66, 0x5b, 0xb6, 0xc0, 0xf1, 0x36, 0x89, 0x65, 0x4c, 0x8e,
	0x32, 0x87, 0xd0, 0x0e, 0xa1, 0x1c, 0xf4, 0x2b, 0x1c, 0x4e, 0x70, 0x37, 0x17, 0x98, 0x5c, 0xa0,
	0x64, 0x3c, 0x14, 0x84, 0x40, 0x33, 0x62, 0x1b, 0x1c, 0x38, 0x43, 0x67, 0xd4, 0xf1, 0xf5, 0x99,
	0x1c, 0x43, 0x0b, 0x37, 0x8c, 0x87, 0x03, 0x57, 0x83, 0x99, 0x41, 0x3c, 0x68, 0x6f, 0x99, 0x10,
	0xbb, 0x38, 0x09, 0x06, 0x0d, 0xed, 0xb8, 0xb3, 0xe9, 0x7b, 0x20, 0x8a, 0xf4, 0x3c, 0x41, 0x26,
	0x79, 0x1c, 0xcd, 0x24, 0x93, 0xa9, 0x20, 0x43, 0xe8, 0xa6, 0x05, 0x8a, 0x81, 0x96, 0x68, 0xfb,
	0x26, 0x44, 0xcf, 0xa1, 0x9f, 0xdf, 0x0b, 0x30, 0x92, 0x9c, 0x85, 0xa2, 0x14, 0x77, 0xf6, 0x89,
	0xbb, 0x35, 0xf1, 0x5b, 0x07, 0x0e, 0xae, 0xe2, 0x15, 0x8f, 0x7c, 0x14, 0xdb, 0x38, 0x12, 0xa8,
	0x84, 0x43, 0x05, 0x64, 0x79, 0x14, 0xc2, 0x06, 0x74, 0x57, 0xb6, 0x6b, 0x94, 0xfd, 0x14, 0x1a,
	0x29, 0x2f, 0x6a, 0x53, 0x47, 0xc5, 0xc3, 0x16, 0x0b, 0x14, 0xe2, 0x26, 0xfe, 0x8d, 0xd1, 0xa0,
	0xa9, 0x3d, 0x26, 0x44, 0x28, 0xf4, 0x12, 0x5c, 0x26, 0x28, 0xd6, 0x59, 0x48, 0x4b, 0x87, 0x54,
	0x30, 0xfa, 0x19, 0x9e, 0xf9, 0x86, 0x5d, 0x74, 0x3e, 0x97, 0x73, 0x4a, 0xb9, 0x3a, 0x99, 0x6b,
	0x21, 0x9b, 0x42, 0x67, 0x82, 0x3b, 0x7d, 0x16, 0xf5, 0xfc, 0x9c, 0x87, 0xf3, 0xb3, 0x51, 0xde,
	0x3a, 0xd0, 0xfd, 0xc8, 0x43, 0x9c, 0xe1, 0x6a, 0x83, 0x91, 0xdc, 0xf3, 0x02, 0x79, 0xba, 0x6e,
	0x99, 0xae, 0x07, 0xed, 0x25, 0x0f, 0x71, 0xa2, 0xfa, 0x98, 0x0f, 0x44, 0x61, 0x3f, 0xa2, 0x73,
	0x23, 0xe8, 0x2f, 0x4b, 0xd1, 0x0b, 0x26, 0x99, 0x6e, 0x5e, 0xcf, 0xaf, 0xc3, 0xf4, 0x0c, 0x7a,
	0xf3, 0x6d, 0x18, 0xb3, 0x20, 0x7f, 0x3b, 0x0a, 0xbd, 0xd4, 0xb0, 0xf3, 0xe7, 0xad, 0x60, 0xf4,
	0x12, 0xba, 0xe6, 0x94, 0xdb, 0x4b, 0xaa, 0x25, 0xe9, 0xde, 0x4b, 0x92, 0x7e, 0xc8, 0x3a, 0xf3,
	0xbf, 0x65, 0x39, 0x81, 0xce, 0x22, 0x9b, 0xe6, 0xeb, 0x8c, 0xa2, 0xe1, 0x97, 0x00, 0xfd, 0x0e,
	0x87, 0x97, 0x7f, 0xe4, 0x43, 0x1c, 0xc7, 0xd0, 0x8a, 0x77, 0x11, 0x26, 0xc5, 0xc2, 0x69, 0xa3,
	0xca, 0xdc, 0xa8, 0x31, 0x9f, 0xfd, 0x6d, 0xc2, 0xd1, 0xbc, 0xbe, 0xf9, 0xe4, 0x07, 0xf4, 0x7d,
	0x5c, 0x71, 0x21, 0x31, 0xc9, 0x17, 0x9d, 0xbc, 0x1e, 0xdf, 0xfb, 0x0e, 0x8c, 0xab, 0x1f, 0x01,
	0xef, 0x8d, 0x25, 0xc4, 0xb2, 0xcf, 0x53, 0xe8, 0xe8, 0x3d, 0xd3, 0xb4, 0x74, 0xff, 0x9d, 0x62,
	0x97, 0xbd, 0xa1, 0x25, 0xa6, 0xba, 0xa9, 0x37, 0xd0, 0xfb, 0x84, 0xb2, 0x9c, 0xe8, 0xb7, 0x96,
	0x1b, 0x96, 0xe5, 0xf1, 0x4e, 0xec, 0x45, 0xe5, 0x2c, 0xd7, 0x00, 0xd9, 0xc4, 0xa8, 0xc6, 0x93,
	0x97, 0x96, 0x58, 0x63, 0xde, 0xbd, 0x57, 0xb6, 0x4a, 0x8c, 0x61, 0x1a, 0x39, 0x64, 0x0a, 0x07,
	0x57, 0x5c, 0x48, 0x55, 0x9f, 0xba, 0x29, 0xac, 0x9c, 0x66, 0x47, 0xf7, 0x69, 0xe6, 0xfe, 0x53,
	0x87, 0xfc, 0x84, 0xe7, 0x8a, 0x72, 0xb6, 0x66, 0x09, 0x06, 0xdf, 0xb8, 0x5c, 0x7f, 0xc1, 0xc7,
	0x51, 0xdb, 0xde, 0xb3, 0x3a, 0x63, 0xa7, 0xce, 0xaf, 0x27, 0xfa, 0x17, 0xf0, 0xee, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9c, 0x82, 0x9b, 0x98, 0x1d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UnitedShieldSpaceClient is the client API for UnitedShieldSpace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnitedShieldSpaceClient interface {
	RegisterNewUser(ctx context.Context, in *NewUserDetails, opts ...grpc.CallOption) (*UserCreationStatus, error)
	LoginUser(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*LoginResponse, error)
	GetNewTokens(ctx context.Context, in *RefreshTokenDetails, opts ...grpc.CallOption) (*NewTokens, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (UnitedShieldSpace_UploadFileClient, error)
	ListUserFiles(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (UnitedShieldSpace_ListUserFilesClient, error)
	ListSharedWithMeFiles(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (UnitedShieldSpace_ListSharedWithMeFilesClient, error)
}

type unitedShieldSpaceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnitedShieldSpaceClient(cc grpc.ClientConnInterface) UnitedShieldSpaceClient {
	return &unitedShieldSpaceClient{cc}
}

func (c *unitedShieldSpaceClient) RegisterNewUser(ctx context.Context, in *NewUserDetails, opts ...grpc.CallOption) (*UserCreationStatus, error) {
	out := new(UserCreationStatus)
	err := c.cc.Invoke(ctx, "/unitedshieldspace.UnitedShieldSpace/RegisterNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitedShieldSpaceClient) LoginUser(ctx context.Context, in *UserCredentials, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/unitedshieldspace.UnitedShieldSpace/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitedShieldSpaceClient) GetNewTokens(ctx context.Context, in *RefreshTokenDetails, opts ...grpc.CallOption) (*NewTokens, error) {
	out := new(NewTokens)
	err := c.cc.Invoke(ctx, "/unitedshieldspace.UnitedShieldSpace/GetNewTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitedShieldSpaceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (UnitedShieldSpace_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UnitedShieldSpace_serviceDesc.Streams[0], "/unitedshieldspace.UnitedShieldSpace/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &unitedShieldSpaceUploadFileClient{stream}
	return x, nil
}

type UnitedShieldSpace_UploadFileClient interface {
	Send(*FileSegment) error
	CloseAndRecv() (*UploadStatus, error)
	grpc.ClientStream
}

type unitedShieldSpaceUploadFileClient struct {
	grpc.ClientStream
}

func (x *unitedShieldSpaceUploadFileClient) Send(m *FileSegment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *unitedShieldSpaceUploadFileClient) CloseAndRecv() (*UploadStatus, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *unitedShieldSpaceClient) ListUserFiles(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (UnitedShieldSpace_ListUserFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UnitedShieldSpace_serviceDesc.Streams[1], "/unitedshieldspace.UnitedShieldSpace/ListUserFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &unitedShieldSpaceListUserFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UnitedShieldSpace_ListUserFilesClient interface {
	Recv() (*FileDetails, error)
	grpc.ClientStream
}

type unitedShieldSpaceListUserFilesClient struct {
	grpc.ClientStream
}

func (x *unitedShieldSpaceListUserFilesClient) Recv() (*FileDetails, error) {
	m := new(FileDetails)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *unitedShieldSpaceClient) ListSharedWithMeFiles(ctx context.Context, in *UserDetails, opts ...grpc.CallOption) (UnitedShieldSpace_ListSharedWithMeFilesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UnitedShieldSpace_serviceDesc.Streams[2], "/unitedshieldspace.UnitedShieldSpace/ListSharedWithMeFiles", opts...)
	if err != nil {
		return nil, err
	}
	x := &unitedShieldSpaceListSharedWithMeFilesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UnitedShieldSpace_ListSharedWithMeFilesClient interface {
	Recv() (*ExtFileDetails, error)
	grpc.ClientStream
}

type unitedShieldSpaceListSharedWithMeFilesClient struct {
	grpc.ClientStream
}

func (x *unitedShieldSpaceListSharedWithMeFilesClient) Recv() (*ExtFileDetails, error) {
	m := new(ExtFileDetails)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UnitedShieldSpaceServer is the server API for UnitedShieldSpace service.
type UnitedShieldSpaceServer interface {
	RegisterNewUser(context.Context, *NewUserDetails) (*UserCreationStatus, error)
	LoginUser(context.Context, *UserCredentials) (*LoginResponse, error)
	GetNewTokens(context.Context, *RefreshTokenDetails) (*NewTokens, error)
	UploadFile(UnitedShieldSpace_UploadFileServer) error
	ListUserFiles(*UserDetails, UnitedShieldSpace_ListUserFilesServer) error
	ListSharedWithMeFiles(*UserDetails, UnitedShieldSpace_ListSharedWithMeFilesServer) error
}

// UnimplementedUnitedShieldSpaceServer can be embedded to have forward compatible implementations.
type UnimplementedUnitedShieldSpaceServer struct {
}

func (*UnimplementedUnitedShieldSpaceServer) RegisterNewUser(ctx context.Context, req *NewUserDetails) (*UserCreationStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewUser not implemented")
}
func (*UnimplementedUnitedShieldSpaceServer) LoginUser(ctx context.Context, req *UserCredentials) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedUnitedShieldSpaceServer) GetNewTokens(ctx context.Context, req *RefreshTokenDetails) (*NewTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewTokens not implemented")
}
func (*UnimplementedUnitedShieldSpaceServer) UploadFile(srv UnitedShieldSpace_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (*UnimplementedUnitedShieldSpaceServer) ListUserFiles(req *UserDetails, srv UnitedShieldSpace_ListUserFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUserFiles not implemented")
}
func (*UnimplementedUnitedShieldSpaceServer) ListSharedWithMeFiles(req *UserDetails, srv UnitedShieldSpace_ListSharedWithMeFilesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSharedWithMeFiles not implemented")
}

func RegisterUnitedShieldSpaceServer(s *grpc.Server, srv UnitedShieldSpaceServer) {
	s.RegisterService(&_UnitedShieldSpace_serviceDesc, srv)
}

func _UnitedShieldSpace_RegisterNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitedShieldSpaceServer).RegisterNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitedshieldspace.UnitedShieldSpace/RegisterNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitedShieldSpaceServer).RegisterNewUser(ctx, req.(*NewUserDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitedShieldSpace_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitedShieldSpaceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitedshieldspace.UnitedShieldSpace/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitedShieldSpaceServer).LoginUser(ctx, req.(*UserCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitedShieldSpace_GetNewTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitedShieldSpaceServer).GetNewTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unitedshieldspace.UnitedShieldSpace/GetNewTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitedShieldSpaceServer).GetNewTokens(ctx, req.(*RefreshTokenDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitedShieldSpace_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UnitedShieldSpaceServer).UploadFile(&unitedShieldSpaceUploadFileServer{stream})
}

type UnitedShieldSpace_UploadFileServer interface {
	SendAndClose(*UploadStatus) error
	Recv() (*FileSegment, error)
	grpc.ServerStream
}

type unitedShieldSpaceUploadFileServer struct {
	grpc.ServerStream
}

func (x *unitedShieldSpaceUploadFileServer) SendAndClose(m *UploadStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *unitedShieldSpaceUploadFileServer) Recv() (*FileSegment, error) {
	m := new(FileSegment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UnitedShieldSpace_ListUserFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserDetails)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UnitedShieldSpaceServer).ListUserFiles(m, &unitedShieldSpaceListUserFilesServer{stream})
}

type UnitedShieldSpace_ListUserFilesServer interface {
	Send(*FileDetails) error
	grpc.ServerStream
}

type unitedShieldSpaceListUserFilesServer struct {
	grpc.ServerStream
}

func (x *unitedShieldSpaceListUserFilesServer) Send(m *FileDetails) error {
	return x.ServerStream.SendMsg(m)
}

func _UnitedShieldSpace_ListSharedWithMeFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserDetails)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UnitedShieldSpaceServer).ListSharedWithMeFiles(m, &unitedShieldSpaceListSharedWithMeFilesServer{stream})
}

type UnitedShieldSpace_ListSharedWithMeFilesServer interface {
	Send(*ExtFileDetails) error
	grpc.ServerStream
}

type unitedShieldSpaceListSharedWithMeFilesServer struct {
	grpc.ServerStream
}

func (x *unitedShieldSpaceListSharedWithMeFilesServer) Send(m *ExtFileDetails) error {
	return x.ServerStream.SendMsg(m)
}

var _UnitedShieldSpace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unitedshieldspace.UnitedShieldSpace",
	HandlerType: (*UnitedShieldSpaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewUser",
			Handler:    _UnitedShieldSpace_RegisterNewUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UnitedShieldSpace_LoginUser_Handler,
		},
		{
			MethodName: "GetNewTokens",
			Handler:    _UnitedShieldSpace_GetNewTokens_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _UnitedShieldSpace_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ListUserFiles",
			Handler:       _UnitedShieldSpace_ListUserFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSharedWithMeFiles",
			Handler:       _UnitedShieldSpace_ListSharedWithMeFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "unitedShieldSpace.proto",
}
